### ISSUE TITLE
Returned Categories Array treated as Object

### ISSUE THREAD

**Issue by m-schreiber** [magesuite/navigation#1]
We have the following Issue after (index:reindex):
```
Fatal error: Uncaught Error: Call to a member function clear() on array in /var/www/vendor/creativestyle/magesuite-navigation/Service/Navigation/Builder.php:82 Stack trace: #0 /var/www/vendor/creativestyle/magesuite-navigation/Service/Navigation/Builder.php(36): MageSuite\Navigation\Service\Navigation\Builder->getChildrenCategories(Object(Magento\Catalog\Model\Category\Interceptor)) #1 /var/www/vendor/magento/framework/Interception/Interceptor.php(58): MageSuite\Navigation\Service\Navigation\Builder->build('2', 'desktop') #2 /var/www/vendor/magento/framework/Interception/Interceptor.php(138): MageSuite\Navigation\Service\Navigation\Builder\Interceptor->___callParent('build', Array) #3 /var/www/vendor/magento/framework/Interception/Interceptor.php(153): MageSuite\Navigation\Service\Navigation\Builder\Interceptor->Magento\Framework\Interception\{closure}('2', 'desktop') #4 /var/www/generated/code/MageSuite/Navigation/Service/Navigation/Builder/Interceptor.php(26): MageSuite\Navigation\Service\Navigation\Builder\Interceptor- in /var/www/vendor/creativestyle/magesuite-navigation/Service/Navigation/Builder.php on line 82
```

It seams to be related to this Code:
https://github.com/magesuite/navigation/blob/fc08da165d7ef332b7bd8fc96cf620be3ab8478b/Service/Navigation/Builder.php#L81

The returned Categories are treated as an Object (Collection) when in fact it's an array. I can not say why that happens, but it seams to be correct according to the DocBlock auf the called function:
vendor/magento/module-catalog/Model/Category.php:984
```
/**
     * Return children categories of current category
     *
     * @return \Magento\Catalog\Model\ResourceModel\Category\Collection|\Magento\Catalog\Model\Category[]
     */
    public function getChildrenCategories()
```

Magento_Catalog Version: 103.0.0

**Comment by diwipl** [comment]
This happens after Category Flat index is enabled.

We're aware, at the moment we're not supporting Category Flat index but we have ticket in backlog to add it's support.

**Comment by m-schreiber** [comment]
thx for the fast response !

`bin/magento config:set --lock-config catalog/frontend/flat_catalog_category 0`

fixed it

**Comment by fritzmg** [comment]
> We're aware, at the moment we're not supporting Category Flat index but we have ticket in backlog to add it's support.

Since this issue still exist (with Magento CE 2.4.2-p1 at least), is this still on the backlog?
