### ISSUE TITLE
Adding template generation timestamp to cache key, so the `/navigation/mobile/index/` can be cached on client

### ISSUE THREAD

**Issue by jtomaszewski** [magesuite/navigation#3]
Currently on each store visit `GET /navigation/mobile/index/?cache_key=...` request is done from the client which returns HTTP 200.

Since it already includes cache key, why don't we make it return 304, so it can be cached forever on the client, to make its' response even faster?

However, we would need to add "template generation timestamp" to the `MageSuite\Navigation\Block\Navigation.getCacheKeyInfo()`, which could be cached between requests in in-memory cache (redis), so that the cache key is changed when `bin/magento cache:clean` is done (e.g. after categories tree is changed).

WDYT? Would u accept PR for that?

**Comment by diwipl** [comment]
Hi

Thank you for bug report.

Navigation result should be cached inside local storage. Request should be done only once per cache key. 

Seems like we might have some bug here with caching.

**Comment by jtomaszewski** [comment]
> Navigation result should be cached inside local storage.

Oh, didn't know about that. Let me revalidate it first.

**Comment by diwipl** [comment]
Ok, I just got confirmation from frontend devs that we no longer cache in local storage because of issues with some browsers.

We rely on varnish caching so there should not be any significant load on backend servers.

**Comment by jtomaszewski** [comment]
> Ok, I just got confirmation from frontend devs that we no longer cache in local storage because of issues with some browsers.

I see. I guess it was because of browsers' local storage memory size limitation?

**Comment by diwipl** [comment]
Yes, exactly.

Some of our customers have quite extensive navigations and it caused problems.
